### ISSUE TITLE
Support for HTTP2 and HTTP3

### ISSUE THREAD

**Issue by dmdhrumilmistry** [owasp-offat/offat#2]
Reference: https://github.com/OWASP/OFFAT/issues/116#issuecomment-2403343802

**Comment by dr4g0n369** [comment]
Thanks for assigning this issue to me. I will start working on http2 first and then add http3.

**Comment by dmdhrumilmistry** [comment]
> Thanks for assigning this issue to me. I will start working on http2 first and then add http3.

Sounds good! LMK if you have any queries related to implementation

**Comment by dr4g0n369** [comment]
I have implemented HTTP/2 using `net/http` and opened a PR. Please check it to view the changes and let me know if I need to make any changes.

**Comment by dmdhrumilmistry** [comment]
> I have implemented HTTP/2 using `net/http` and opened a PR. Please check it to view the changes and let me know if I need to make any changes.

Merged 🥳

**Comment by dr4g0n369** [comment]
Thanks so much
That was my first PR 🥳😁

**Comment by dmdhrumilmistry** [comment]
> Thanks so much That was my first PR 🥳😁

Thanks for contributing to the project!

**Comment by dr4g0n369** [comment]
I have implemented HTTP/3 using `quic-go`. Please see if any changes are needed.

**Comment by dmdhrumilmistry** [comment]
Thanks for the contribution 🥳. I've merged the PR. Closing this issue!
